version: "3"

services:

    bot:
        build: .
        depends_on:
            - database
        volumes:
            - ./src:/app

    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: olx

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - database
